### ISSUE TITLE
Provide a set of sudoers rules for deploy users

### ISSUE THREAD

**Issue by mberkowski** [umn-ansible/umn_user_management_role#2]
Unlike old swadm who had full sudo, deploy users should be given only what they need.

Add a `sudo_rules` property to deploy users which accepts a list of things they can do, and template out a file in sudoers.d accordingly.

**Comment by cmcfadden** [comment]
This would be nice - I was wishing for this earlier this week.

**Comment by mberkowski** [comment]
Totally! But I'm not sure whether it should be generalized in this role or if it would be better to bundle privileges specific to tasks performed by other roles? e.g. the web app role, should it create permissions for a user who needs to be able to restart nginx or should this role do it?

**Comment by cmcfadden** [comment]
I don't think it's unreasonable to handle it in this role - personally I'd rather have a single place to look to get a sense of what a user is capable of, rathe than having to piece it together across multiple roles. But I can see the argument for the alternative.

**Comment by nihiliad** [comment]
I presume we would use the [sudoers module](https://docs.ansible.com/ansible/latest/collections/community/general/sudoers_module.html), or something like it, to make the changes to sudoers. As long as we're not re-inventing that wheel, at least not without a good reason, I think it's fine to keep the privileges with the associated user roles.
